# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 11:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='best_submission_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='problems_data',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=15000)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest_data')),
            ],
        ),
        migrations.CreateModel(
            name='submission_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=20000)),
                ('lang', models.CharField(max_length=10)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='testcase_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('score', models.IntegerField()),
                ('input', models.FileField(null=True, upload_to=b'')),
                ('output', models.FileField(null=True, upload_to=b'')),
                ('time_limit', models.IntegerField(default=1)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems_data')),
            ],
        ),
        migrations.CreateModel(
            name='testcase_submission_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.submission_data')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.testcase_data')),
            ],
        ),
        migrations.AddField(
            model_name='best_submission_data',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems_data'),
        ),
        migrations.AddField(
            model_name='best_submission_data',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.submission_data'),
        ),
        migrations.AddField(
            model_name='best_submission_data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user_data'),
        ),
    ]
